import os
import io
import json
import datetime
import requests
import numpy as np
import pandas as pd
import yfinance as yf

# Environment Variables (Configurable via GCP Cloud Run Function)
SLACK_WEBHOOK_URL = os.environ.get("SLACK_WEBHOOK_URL", "https://hooks.slack.com/services/YOUR/WEBHOOK/URL")
DEFAULT_CAPITAL = float(os.environ.get("PORTFOLIO_CAPITAL", 10000.0))
MAX_PER_SECTOR = int(os.environ.get("MAX_PER_SECTOR", 2))
PORTFOLIO_SIZE = int(os.environ.get("PORTFOLIO_SIZE", 10))


def get_sp500_universe():
    """Fetches current S&P 500 tickers and sector mapping."""
    try:
        url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
        headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}
        res = requests.get(url, headers=headers, timeout=10)
        res.raise_for_status()
        tables = pd.read_html(io.StringIO(res.text))
        df = tables[0][['Symbol', 'Security', 'GICS Sector']].copy()
        df.columns = ['Ticker', 'Company', 'Sector']
        df['Ticker'] = df['Ticker'].str.replace('.', '-', regex=False)
        return df
    except Exception as e:
        print(f"Fallback to static CSV universe due to: {e}")
        url = 'https://raw.githubusercontent.com/datasets/s-and-p-500-companies/main/data/constituents.csv'
        df = pd.read_csv(url)
        df['Symbol'] = df['Symbol'].str.replace('.', '-', regex=False)
        return df.rename(columns={'Symbol': 'Ticker', 'Name': 'Company', 'Sector': 'Sector'})


def send_slack_notification(target_df, total_capital):
    """Formats the rebalance output into a clean Slack Block Kit message and sends it."""
    today = datetime.datetime.now().strftime("%Y-%m-%d")
    
    # Format individual position strings
    rows = []
    for _, r in target_df.iterrows():
        rows.append(
            f"• *#{r['Rank']} {r['Ticker']}* ({r['Sector']}) | "
            f"Weight: *{r['Target_Weight_%']}%* (~${r['Target_Value_$']:,.0f}) | "
            f"Price: ${r['Latest_Price']:.2f} | "
            f"6M Mom: *+{r['6M_Momentum_%']}%*"
        )
    positions_str = "\n".join(rows)

    slack_payload = {
        "blocks": [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": f"📈 Weekly Rebalance Signal - {today}",
                    "emoji": True
                }
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Portfolio Value Target:* `${total_capital:,.2f}`\n"
                            f"*Strategy Rules:* Top {PORTFOLIO_SIZE} Stocks | 6-Month Momentum Heavy | 200-SMA Gate | Max {MAX_PER_SECTOR}/Sector"
                }
            },
            {"type": "divider"},
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Target Portfolio Rankings (Weekly Update):*\n{positions_str}"
                }
            },
            {"type": "divider"},
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": "🤖 Automated signal generated by GCP Cloud Run Function."
                    }
                ]
            }
        ]
    }

    res = requests.post(
        SLACK_WEBHOOK_URL, 
        data=json.dumps(slack_payload),
        headers={'Content-Type': 'application/json'},
        timeout=10
    )
    res.raise_for_status()


def run_rebalance_function(request):
    """GCP Cloud Run Function Entry Point (HTTP Triggered)."""
    try:
        # Parse optional JSON payload from request (e.g. {"capital": 15000})
        req_json = request.get_json(silent=True) or {}
        total_capital = float(req_json.get('capital', DEFAULT_CAPITAL))

        today_dt = datetime.datetime.now()
        today_str = today_dt.strftime("%Y-%m-%d")
        
        print(f"Executing weekly rebalance run for date: {today_str}")

        # 1. Fetch Universe
        sp_df = get_sp500_universe()
        tickers = sp_df['Ticker'].tolist()

        # 2. Fetch Historical Price Data (1 year window)
        start_dt = today_dt - datetime.timedelta(days=365)
        hist_prices = yf.download(
            tickers, 
            start=start_dt.strftime("%Y-%m-%d"), 
            end=today_str, 
            progress=False, 
            auto_adjust=True
        )

        close_prices = hist_prices['Close'] if 'Close' in hist_prices.columns else hist_prices['Adj Close']
        close_prices = close_prices.ffill().dropna(how='all', axis=1)

        # 3. Calculate Momentum & Technical Filters
        valid_rows = []
        for _, sp_row in sp_df.iterrows():
            sym = sp_row['Ticker']
            if sym not in close_prices.columns:
                continue

            series = close_prices[sym].dropna()
            if len(series) < 126:  # Need ~6 months of trading days
                continue

            latest_p = series.iloc[-1]
            sma_200 = series.iloc[-min(len(series), 200):].mean()

            # Technical Trend Gate: Price must be strictly above 200-day SMA
            if latest_p < sma_200:
                continue

            # 6-Month Momentum calculation (126 trading days)
            mom_6m = ((latest_p - series.iloc[-126]) / series.iloc[-126]) * 100.0

            valid_rows.append({
                'Ticker': sym,
                'Company': sp_row['Company'],
                'Sector': sp_row['Sector'],
                'Latest_Price': round(latest_p, 2),
                '6M_Momentum_%': round(mom_6m, 2)
            })

        df_cand = pd.DataFrame(valid_rows)
        if df_cand.empty:
            return "No candidates passed the 200-SMA momentum criteria today.", 200

        # Sort candidates descending by 6-Month Momentum
        df_cand.sort_values(by='6M_Momentum_%', ascending=False, inplace=True)

        # 4. Apply Sector Diversification Constraints (Max 2 per Sector, Top 10 Overall)
        selected, sector_counts = [], {}
        for _, row in df_cand.iterrows():
            sec = row['Sector']
            if sector_counts.get(sec, 0) < MAX_PER_SECTOR:
                selected.append(row)
                sector_counts[sec] = sector_counts.get(sec, 0) + 1
            if len(selected) == PORTFOLIO_SIZE:
                break

        res_df = pd.DataFrame(selected).reset_index(drop=True)
        res_df['Rank'] = res_df.index + 1

        # Calculate exponential weights based on 6M Momentum
        raw_w = res_df['6M_Momentum_%'] ** 1.5
        res_df['Target_Weight_%'] = ((raw_w / raw_w.sum()) * 100.0).round(2)
        res_df['Target_Value_$'] = (total_capital * (res_df['Target_Weight_%'] / 100.0)).round(2)

        # 5. Dispatch Payload to Slack
        send_slack_notification(res_df, total_capital=total_capital)

        print("Weekly rebalance signal successfully posted to Slack.")
        return f"Successfully generated weekly momentum signal and posted to Slack for {today_str}.", 200

    except Exception as e:
        err_msg = f"Error executing weekly rebalance signal: {str(e)}"
        print(err_msg)
        return err_msg, 500


# For testing locally via python main.py
if __name__ == "__main__":
    class DummyRequest:
        def get_json(self, silent=True):
            return {"capital": 10000.0}

    print("Running local test execution...")
    status_text, code = run_rebalance_function(DummyRequest())
    print(f"Status Code: {code} | Message: {status_text}")
